//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrade.Similarity.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andrade.Similarity.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name where will be search the term..
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_ColumnName_Description {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_ColumnName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name.
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_ColumnName_DisplayName {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_ColumnName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data table that where will be search the term..
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_DataTable_Description {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_DataTable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable.
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_DataTable_DisplayName {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_DataTable_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look for similarity between terms in a Data Table..
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_Description {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity between terms in a Data Table.
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_DisplayName {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity that was found..
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_FoundSimilarity_Description {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_FoundSimilarity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found similarity.
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_FoundSimilarity_DisplayName {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_FoundSimilarity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term that was found..
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_FoundTerm_Description {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_FoundTerm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found term.
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_FoundTerm_DisplayName {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_FoundTerm_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this parameter to &quot;True&quot; if you want to look for the biggest similarity term in the entire Data Table. Set this parameter to &quot;False&quot; if you just want to get the term that hit the similarity defined..
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_LookForTheBiggestSimilarity_Description {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_LookForTheBiggestSimilarity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look for the biggest similarity.
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_LookForTheBiggestSimilarity_DisplayName {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_LookForTheBiggestSimilarity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity that you want to be found..
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_SimilarityToBeFound_Description {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_SimilarityToBeFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity to be found.
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_SimilarityToBeFound_DisplayName {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_SimilarityToBeFound_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term that you&apos;d like to be found.
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_TermToBeFound_Description {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_TermToBeFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term to be found.
        /// </summary>
        public static string SimilarityBetweenTermsInADataTable_TermToBeFound_DisplayName {
            get {
                return ResourceManager.GetString("SimilarityBetweenTermsInADataTable_TermToBeFound_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
